name: 'NewTaggedRelease'
description: 'Creates a new tagged release'
author: 'Jeff Patton'

branding:
  icon: 'activity'
  color: 'blue'

inputs:
  name:
    description: 'The name of the release'
    required: false
    type: string
  version:
    description: 'The version number of the release'
    required: true
    type: string
  verbose:
    description: "A value of verbose will output additional information"
    required: false
    type: string
    default: 'None'
  github_token:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        VERBOSE: ${{ inputs.verbose }}
      run: |
        & $env:GITHUB_ACTION_PATH\\newtaggedrelease.ps1 -Name ${{ inputs.name }} -Version ${{ inputs.version }}
      shell: pwsh
