name: 'NewTaggedRelease'
description: 'Creates a new tagged release'
author: 'Jeff Patton'

branding:
  icon: 'activity'
  color: 'blue'

inputs:
  version:
    description: 'The version number of the release'
    required: true
    type: string
  name:
    description: 'The name of the release'
    required: false
    type: string
  body:
    description: 'The body of the release'
    required: true
    type: string
  prerelease:
    description: 'Mark this as a pre-prerelease'
    required: false
    type: bool
    default: false
  releasenotes:
    description: 'Add the generated releasenotes'
    required: false
    type: boolean
    default: true
  verbose:
    description: "A value of verbose will output additional information"
    required: false
    type: string
    default: 'None'
  github_token:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        VERBOSE: ${{ inputs.verbose }}
      run: |
        & $env:GITHUB_ACTION_PATH\\newtaggedrelease.ps1 -Name ${{ inputs.name }} -Version ${{ inputs.version }} -Body ${{ inputs.body }} -PreRelease ${{ inputs.prerelease }} -ReleaseNotes ${{ inputs.releasenotes}}
      shell: pwsh
