name: Reusable Release Workflow

on:
  workflow_call:
    inputs:
      source_path:
        required: true
        type: string
      project_name:
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitpython requests

      - name: Run the release script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python path/to/newtaggedrelease.py ${{ inputs.source_path }} ${{ inputs.project_name }}
